// Sample data for properties
import img1 from './assets/img1.jpeg';
import img2 from './assets/img2.jpeg';
import img3 from'./assets/img3.jpeg';
import img4 from './assets/img4.jpeg';
import img5 from './assets/img5.jpeg';
import img6 from './assets/img6.jpeg';
import img7 from './assets/img7.jpeg';
import img8 from './assets/img8.jpeg';
import img9 from './assets/img9.jpeg';
import img10 from './assets/img10.jpeg';

import agent1 from './assets/agent1.jpeg';
import agent2 from './assets/agent2.jpeg';
import agent3 from './assets/agent3.jpeg';
import agent4 from './assets/agent4.jpeg';
import agent5 from './assets/agent5.jpeg';
import agent6 from './assets/agent6.jpeg';
import agent7 from './assets/agent7.jpeg';
import agent8 from './assets/agent8.jpeg';
import agent9 from './assets/agent9.jpeg';
import agent10 from './assets/agent10.jpeg';


export const properties = [
    {
        id: 1,
        name: 'Love palace',
        location: 'Delhi',
        price: 250000,
        type: 'rent',
        dimensions: '1500 sqft',
        image: img7,
        description: 'A beautiful villa with green surroundings.',
        bedroomType: '3 BHK',
        agentId: 1,
    },
    {
        id: 2,
        name: 'Ocean View',
        location: 'Goa',
        price: 180000,
        type: 'rent',
        dimensions: '1200 sqft',
        image: img2,
        description: 'An apartment with a stunning ocean view.',
        bedroomType: '2BHK',
        agentId: 2,
    },
    {
        id: 3,
        name: 'Urban Nest',
        location: 'Delhi',
        price: 300000,
        type: 'sale',
        dimensions: '1400 sqft',
        image: img3,
        description: 'Modern apartment in the heart of the city.',
        bedroomType: '3 BHK',
        agentId: 3,
    },
    {
        id: 4,
        name: 'Cozy Cottage',
        location: 'Shimla',
        price: 200000,
        type: 'rent',
        dimensions: '1300 sqft',
        image: img4,
        description: 'A quaint cottage with a cozy atmosphere.',
        bedroomType: '2 BHK',
        agentId: 4,
    },
    {
        id: 5,
        name: 'Luxury Loft',
        location: 'Bangalore',
        price: 350000,
        type: 'sale',
        dimensions: '1600 sqft',
        image: img5,
        description: 'A stylish loft with high-end finishes.',
        bedroomType: '1 BHK',
        agentId: 5,
    },
    {
        id: 6,
        name: 'Mountain Retreat',
        location: 'Manali',
        price: 275000,
        type: 'sale',
        dimensions: '1800 sqft',
        image: img6,
        description: 'A spacious retreat with breathtaking mountain views.',
        bedroomType: '3 BHK',
        agentId: 6,
    },
    {
        id: 7,
        name: 'City Penthouse',
        location: 'Mumbai',
        price: 500000,
        type: 'sale',
        dimensions: '2000 sqft',
        image: img7,
        description: 'An upscale penthouse with panoramic city views.',
        bedroomType: '3 BHK',
        agentId: 7,
    },
    {
        id: 8,
        name: 'Beachside Villa',
        location: 'Goa',
        price: 400000,
        type: 'rent',
        dimensions: '1700 sqft',
        image: img8,
        description: 'A luxurious villa right on the beach.',
        bedroomType: '2 BHK',
        agentId: 8,
    },
    {
        id: 9,
        name: 'Historic Mansion',
        location: 'Delhi',
        price: 450000,
        type: 'sale',
        dimensions: '2500 sqft',
        image: img9,
        description: 'An elegant mansion with historic charm.',
        bedroomType: '3 BHK',
        agentId: 9,
    },
    {
        id: 10,
        name: 'Urban Loft',
        location: 'Bangalore',
        price: 320000,
        type: 'sale',
        dimensions: '1550 sqft',
        image: img10,
        description: 'A contemporary loft with urban amenities.',
        bedroomType: '1 BHK',
        agentId: 10,
    },  {
        id: 11,
        name: 'cozy Cottage house',
        location: 'Shimla',
        price: 350000,
        type: 'sale',
        dimensions: '1300 sqft',
        image: img5,
        description: 'A quaint cottage with a cozy atmosphere.',
        bedroomType: '2 BHK',
        agentId: 6,
    },
    {
    id: 12,
    name: 'Luxury Soft',
    location: 'Bangalore',
    price: 380000,
    type: 'sale',
    dimensions: '1600 sqft',
    image: img8,
    description: 'A stylish loft with high-end finishes.',
    bedroomType: '1 BHK',
    agentId: 4,
    },
    {
        id: 13,
        name: 'Historic Mansion stream',
        location: 'Delhi',
        price: 450000,
        type: 'rent',
        dimensions: '2500 sqft',
        image: img9,
        description: 'An elegant mansion with historic charm.',
        bedroomType: '3 BHK',
        agentId: 10,
    }

];

// Sample data for agents

export const agents = [
    {
        id: 1,
        name: 'John Doe',
        email: 'john.doe@example.com',
        phone: '9234567890',
        profilePicture: agent1,
        bio: 'Experienced real estate agent specializing in luxury properties.',
    },
    {
        id: 2,
        name: 'Jane Smith',
        email: 'jane.smith@example.com',
        phone: '9987654321',
        profilePicture: agent2,
        bio: 'Skilled agent with a passion for finding perfect homes.',
    },
    {
        id: 3,
        name: 'Alice Johnson',
        email: 'alice.johnson@example.com',
        phone: '9122334455',
        profilePicture: agent3,
        bio: 'Dedicated agent with extensive knowledge of the local market.',
    },
    {
        id: 4,
        name: 'Michael Brown',
        email: 'michael.brown@example.com',
        phone: '9234567891',
        profilePicture: agent4,
        bio: 'Expert in commercial real estate with a track record of successful deals.',
    },
    {
        id: 5,
        name: 'Emily Davis',
        email: 'emily.davis@example.com',
        phone: '9987654322',
        profilePicture: agent5,
        bio: 'Friendly agent specializing in residential properties.',
    },
    {
        id: 6,
        name: 'Chris Wilson',
        email: 'chris.wilson@example.com',
        phone: '9122334456',
        profilePicture: agent6,
        bio: 'Experienced in both buying and selling real estate.',
    },
    {
        id: 7,
        name: 'Olivia Martinez',
        email: 'olivia.martinez@example.com',
        phone: '9234567892',
        profilePicture: agent7,
        bio: 'Passionate about finding the perfect home for clients.',
    },
    {
        id: 8,
        name: 'Ethan Lewis',
        email: 'ethan.lewis@example.com',
        phone: '9987654323',
        profilePicture: agent8,
        bio: 'Seasoned agent with extensive knowledge of luxury markets.',
    },
    {
        id: 9,
        name: 'Sophia Taylor',
        email: 'sophia.taylor@example.com',
        phone: '9122334457',
        profilePicture: agent9,
        bio: 'Detail-oriented agent with a focus on customer satisfaction.',
    },
    {
        id: 10,
        name: 'Liam Anderson',
        email: 'liam.anderson@example.com',
        phone: '9234567893',
        profilePicture: agent10,
        bio: 'Dedicated professional with a keen eye for investment opportunities.',
    },
];

// Sample data for transactions
export const transactions = [
    {
        id: 1,
        propertyId: 1,
        userId: 101,
        transactionType: 'buy',
        amount: 250000,
        paymentMethod: 'upi',
        date: '2024-08-01',
    },
    {
        id: 2,
        propertyId: 2,
        userId: 102,
        transactionType: 'rent',
        amount: 180000,
        paymentMethod: 'netbanking',
        date: '2024-08-05',
    },
    {
        id: 3,
        propertyId: 3,
        userId: 103,
        transactionType: 'buy',
        amount: 300000,
        paymentMethod: 'credit card',
        date: '2024-08-10',
    },
    {
        id: 4,
        propertyId: 4,
        userId: 104,
        transactionType: 'rent',
        amount: 200000,
        paymentMethod: 'upi',
        date: '2024-08-12',
    },
    {
        id: 5,
        propertyId: 5,
        userId: 105,
        transactionType: 'buy',
        amount: 350000,
        paymentMethod: 'netbanking',
        date: '2024-08-15',
    },
    {
        id: 6,
        propertyId: 6,
        userId: 106,
        transactionType: 'buy',
        amount: 275000,
        paymentMethod: 'credit card',
        date: '2024-08-18',
    },
    {
        id: 7,
        propertyId: 7,
        userId: 107,
        transactionType: 'buy',
        amount: 500000,
        paymentMethod: 'upi',
        date: '2024-08-20',
    },
    {
        id: 8,
        propertyId: 8,
        userId: 108,
        transactionType: 'buy',
        amount: 400000,
        paymentMethod: 'netbanking',
        date: '2024-08-22',
    },
    {
        id: 9,
        propertyId: 9,
        userId: 109,
        transactionType: 'buy',
        amount: 450000,
        paymentMethod: 'credit card',
        date: '2024-08-25',
    },
    {
        id: 10,
        propertyId: 10,
        userId: 110,
        transactionType: 'buy',
        amount: 320000,
        paymentMethod: 'upi',
        date: '2024-08-28',
    },
];
